# File: .markdownlint.yaml
# Role: Markdown lint configuration
# Authority: Tooling configuration
# Governed by: AGENTS.md
# Additional instructions: Disable line length (MD013) and allow agent metadata
# blocks to appear before the first heading (MD041).
---
MD013: false
MD041: false
