# SwiftLint Configuration
# https://github.com/realm/SwiftLint

# Include only iOS source code
included:
  - ios/Offload

# Exclude build artifacts and generated code
excluded:
  - ios/Offload.xcodeproj
  - ios/DerivedData
  - ios/**/DerivedData
  - .build
  - **/.build

# Reporter type for GitHub Actions
reporter: "github-actions-logging"

# Enabled rules (standard set)
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Disabled rules (only when necessary)
disabled_rules:
  # Add rules here only if conflicts arise during testing

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
  excluded:
    - id
    - url
    - db

# Require explicit type annotations for API boundaries
# (can be adjusted based on team preference)
force_unwrapping: error
implicitly_unwrapped_optional: warning
