# Intent: Collect consistent bug reports for Offload.

---
name: Bug report
description: Report a problem or regression.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the problem.
      placeholder: What went wrong?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the steps so we can reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Tap ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your device and OS.
      placeholder: |
        - Device:
        - iOS version:
        - App build/commit:
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Screenshots, logs, or any other context.
    validations:
      required: false
