# Intent: Collect structured feature requests for Offload.

name: Feature request
description: Suggest an idea or improvement.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share an idea.
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem are you trying to solve?
      placeholder: Describe the pain or workflow gap.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you have considered.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Mockups, screenshots, or supporting details.
    validations:
      required: false
